"""Seed reference data: dim_time, metric_registry, feature_registry.

Usage:
    uv run python scripts/seed_registries.py

Idempotent — safe to re-run (uses ON CONFLICT DO NOTHING).
"""

import asyncio
import sys
from datetime import date, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from sqlalchemy import text  # noqa: E402

from app.infrastructure.database.session import engine  # noqa: E402

TIME_START = date(2020, 1, 1)
TIME_END = date(2030, 12, 31)

# 50 standardized KPIs across six categories (03_DATABASE.md §8.1 + PRD Part IV §4)
METRICS: list[tuple[str, str, str, str, str, str, str, str]] = [
    # (metric_name, category, business_definition, formula, unit, data_source, refresh_cron, owner)
    # --- Customer (10) ---
    (
        "active_customers",
        "customer",
        "Number of customers with active status",
        "COUNT(DISTINCT customer_id) WHERE status='active'",
        "count",
        "warehouse.dim_customer",
        "0 2 * * *",
        "Analytics",
    ),
    (
        "new_customers",
        "customer",
        "Customers who joined in the period",
        "COUNT(customer_id) WHERE join_date IN period",
        "count",
        "warehouse.dim_customer",
        "0 2 * * *",
        "Analytics",
    ),
    (
        "churned_customers",
        "customer",
        "Customers who churned in the period",
        "COUNT(customer_id) WHERE status='churned' AND churn_date IN period",
        "count",
        "warehouse.dim_customer",
        "0 2 * * *",
        "Analytics",
    ),
    (
        "customer_growth_rate",
        "customer",
        "Net customer growth rate",
        "(new - churned) / customers_at_start",
        "%",
        "warehouse.dim_customer",
        "0 2 * * *",
        "Analytics",
    ),
    (
        "retention_rate",
        "customer",
        "Share of customers retained over period",
        "retained / customers_at_start",
        "%",
        "warehouse.dim_customer",
        "0 2 * * *",
        "Analytics",
    ),
    (
        "churn_rate",
        "customer",
        "Share of customers lost over period",
        "lost / customers_at_start",
        "%",
        "warehouse.dim_customer",
        "0 2 * * *",
        "Analytics",
    ),
    (
        "customer_lifetime",
        "customer",
        "Average customer tenure",
        "AVG(tenure_days) / 30.44",
        "months",
        "feature_store.customer_features",
        "0 3 * * *",
        "Analytics",
    ),
    (
        "clv",
        "customer",
        "Customer Lifetime Value",
        "ARPU * gross_margin * expected_lifetime",
        "USD",
        "semantic.kpi_arpu + dim_customer",
        "0 3 * * *",
        "Analytics",
    ),
    (
        "at_risk_customers",
        "customer",
        "Customers with churn risk score >= 0.6",
        "COUNT(customer_id) WHERE risk_score >= 0.6",
        "count",
        "ml.prediction_registry",
        "0 4 * * *",
        "ML",
    ),
    (
        "premium_customers",
        "customer",
        "Customers on premium packages",
        "COUNT(customer_id) WHERE package_type='premium'",
        "count",
        "warehouse.dim_package",
        "0 2 * * *",
        "Analytics",
    ),
    # --- Revenue (10) ---
    (
        "arpu",
        "revenue",
        "Average revenue per active customer",
        "SUM(net_revenue) / COUNT(DISTINCT customer_id)",
        "USD",
        "semantic.kpi_arpu",
        "0 2 * * *",
        "Analytics",
    ),
    (
        "mrr",
        "revenue",
        "Monthly Recurring Revenue",
        "SUM(net_revenue) for billing_month",
        "USD",
        "semantic.kpi_revenue",
        "0 2 * * *",
        "Analytics",
    ),
    (
        "revenue_growth_rate",
        "revenue",
        "MoM revenue growth",
        "(mrr_current - mrr_previous) / mrr_previous",
        "%",
        "semantic.kpi_revenue",
        "0 2 * * *",
        "Analytics",
    ),
    (
        "package_revenue",
        "revenue",
        "Revenue attributed to each package",
        "SUM(net_revenue) GROUP BY package",
        "USD",
        "warehouse.fact_billing",
        "0 2 * * *",
        "Analytics",
    ),
    (
        "upsell_revenue",
        "revenue",
        "Revenue from package upgrades",
        "SUM(net_revenue - previous_net_revenue) WHERE package upgrade",
        "USD",
        "warehouse.fact_billing",
        "0 2 * * *",
        "Analytics",
    ),
    (
        "average_discount",
        "revenue",
        "Average discount amount per customer",
        "AVG(discount_amount)",
        "USD",
        "warehouse.fact_billing",
        "0 2 * * *",
        "Analytics",
    ),
    (
        "discount_ratio",
        "revenue",
        "Average discount as share of price",
        "AVG(discount_amount / package_price)",
        "%",
        "warehouse.fact_billing",
        "0 2 * * *",
        "Analytics",
    ),
    (
        "net_revenue",
        "revenue",
        "Total revenue after discounts",
        "SUM(monthly_fee - discount_amount)",
        "USD",
        "warehouse.fact_billing",
        "0 2 * * *",
        "Analytics",
    ),
    (
        "gross_margin",
        "revenue",
        "Revenue minus direct costs",
        "(revenue - direct_costs) / revenue",
        "%",
        "warehouse.fact_billing",
        "0 2 * * *",
        "Analytics",
    ),
    (
        "arpu_by_region",
        "revenue",
        "ARPU segmented by region",
        "SUM(net_revenue)/COUNT(DISTINCT customer_id) GROUP BY region",
        "USD",
        "semantic.kpi_arpu",
        "0 2 * * *",
        "Analytics",
    ),
    # --- Usage (8) ---
    (
        "avg_daily_data",
        "usage",
        "Average daily data usage per active customer",
        "AVG(data_usage_mb)",
        "MB",
        "warehouse.fact_usage_daily",
        "0 3 * * *",
        "Analytics",
    ),
    (
        "avg_daily_voice",
        "usage",
        "Average daily voice minutes per customer",
        "AVG(voice_minutes)",
        "min",
        "warehouse.fact_usage_daily",
        "0 3 * * *",
        "Analytics",
    ),
    (
        "avg_daily_sms",
        "usage",
        "Average daily SMS count per customer",
        "AVG(sms_count)",
        "count",
        "warehouse.fact_usage_daily",
        "0 3 * * *",
        "Analytics",
    ),
    (
        "roaming_usage",
        "usage",
        "Total roaming data consumed",
        "SUM(roaming_usage_mb)",
        "MB",
        "warehouse.fact_usage_daily",
        "0 3 * * *",
        "Analytics",
    ),
    (
        "peak_usage_ratio",
        "usage",
        "Share of usage during peak hours",
        "SUM(peak_usage_mb) / SUM(data_usage_mb)",
        "%",
        "warehouse.fact_usage_daily",
        "0 3 * * *",
        "Analytics",
    ),
    (
        "night_usage_ratio",
        "usage",
        "Share of usage during night hours",
        "SUM(night_usage_mb) / SUM(data_usage_mb)",
        "%",
        "warehouse.fact_usage_daily",
        "0 3 * * *",
        "Analytics",
    ),
    (
        "weekend_usage_ratio",
        "usage",
        "Share of usage on weekends",
        "SUM(weekend_usage) / SUM(data_usage)",
        "%",
        "warehouse.fact_usage_daily",
        "0 3 * * *",
        "Analytics",
    ),
    (
        "data_quota_utilization",
        "usage",
        "Share of data quota consumed",
        "avg_daily_data * 30 / data_quota",
        "%",
        "feature_store.customer_features",
        "0 3 * * *",
        "Analytics",
    ),
    # --- Network (6) ---
    (
        "drop_rate",
        "network",
        "Average call drop rate",
        "AVG(drop_rate)",
        "%",
        "warehouse.fact_network",
        "0 3 * * *",
        "Network",
    ),
    (
        "avg_latency",
        "network",
        "Average network latency",
        "AVG(latency_ms)",
        "ms",
        "warehouse.fact_network",
        "0 3 * * *",
        "Network",
    ),
    (
        "coverage_score",
        "network",
        "Average coverage quality",
        "AVG(coverage_score)",
        "score",
        "warehouse.fact_network",
        "0 3 * * *",
        "Network",
    ),
    (
        "signal_strength",
        "network",
        "Average signal quality",
        "AVG(signal_strength)",
        "score",
        "warehouse.fact_network",
        "0 3 * * *",
        "Network",
    ),
    (
        "packet_loss",
        "network",
        "Average packet loss rate",
        "AVG(packet_loss)",
        "%",
        "warehouse.fact_network",
        "0 3 * * *",
        "Network",
    ),
    (
        "service_availability",
        "network",
        "Share of time service is available",
        "1 - AVG(drop_rate) - AVG(packet_loss)",
        "%",
        "warehouse.fact_network",
        "0 3 * * *",
        "Network",
    ),
    # --- Service (8) ---
    (
        "complaint_count",
        "service",
        "Total complaints in period",
        "SUM(ticket_count)",
        "count",
        "warehouse.fact_service",
        "0 3 * * *",
        "Service",
    ),
    (
        "ticket_resolution_time",
        "service",
        "Average time to resolve tickets",
        "AVG(resolution_time_min)",
        "min",
        "warehouse.fact_service",
        "0 3 * * *",
        "Service",
    ),
    (
        "csat",
        "service",
        "Average customer satisfaction score",
        "AVG(csat_score)",
        "score",
        "warehouse.fact_service",
        "0 3 * * *",
        "Service",
    ),
    (
        "first_response_time",
        "service",
        "Average time to first response",
        "AVG(waiting_time_min)",
        "min",
        "warehouse.fact_service",
        "0 3 * * *",
        "Service",
    ),
    (
        "escalation_rate",
        "service",
        "Share of tickets escalated",
        "SUM(CASE WHEN escalation_count>0 THEN 1 ELSE 0 END) / COUNT(*)",
        "%",
        "warehouse.fact_service",
        "0 3 * * *",
        "Service",
    ),
    (
        "complaint_by_type",
        "service",
        "Complaints grouped by type",
        "COUNT(*) GROUP BY complaint_type",
        "count",
        "warehouse.fact_service",
        "0 3 * * *",
        "Service",
    ),
    (
        "resolution_rate",
        "service",
        "Share of tickets resolved within SLA",
        "resolved_in_sla / total_tickets",
        "%",
        "warehouse.fact_service",
        "0 3 * * *",
        "Service",
    ),
    (
        "csat_trend",
        "service",
        "MoM change in CSAT",
        "csat_current - csat_previous",
        "delta",
        "warehouse.fact_service",
        "0 3 * * *",
        "Service",
    ),
    # --- Marketing (8) ---
    (
        "campaign_roi",
        "marketing",
        "Return on campaign investment",
        "(campaign_revenue - campaign_cost) / campaign_cost",
        "ratio",
        "warehouse.fact_campaign",
        "0 3 * * 1",
        "Marketing",
    ),
    (
        "promotion_conversion",
        "marketing",
        "Share of campaign touches that convert",
        "SUM(CASE WHEN converted THEN 1 ELSE 0 END) / COUNT(*)",
        "%",
        "warehouse.fact_campaign",
        "0 3 * * 1",
        "Marketing",
    ),
    (
        "coupon_usage",
        "marketing",
        "Share of touches with coupon redeemed",
        "SUM(CASE WHEN coupon_used THEN 1 ELSE 0 END) / COUNT(*)",
        "%",
        "warehouse.fact_campaign",
        "0 3 * * 1",
        "Marketing",
    ),
    (
        "cac",
        "marketing",
        "Customer acquisition cost",
        "total_campaign_cost / new_customers",
        "USD",
        "warehouse.fact_campaign",
        "0 3 * * 1",
        "Marketing",
    ),
    (
        "retention_campaign_success",
        "marketing",
        "Churn reduction attributable to retention campaigns",
        "baseline_churn - campaign_churn",
        "%",
        "warehouse.fact_campaign",
        "0 3 * * 1",
        "Marketing",
    ),
    (
        "campaign_revenue",
        "marketing",
        "Revenue attributed to campaigns",
        "SUM(revenue_attributed) FROM campaign touches",
        "USD",
        "warehouse.fact_campaign",
        "0 3 * * 1",
        "Marketing",
    ),
    (
        "channel_conversion",
        "marketing",
        "Conversion by delivery channel",
        "SUM(converted) GROUP BY channel",
        "%",
        "warehouse.fact_campaign",
        "0 3 * * 1",
        "Marketing",
    ),
    (
        "campaign_cost",
        "marketing",
        "Total campaign spend",
        "SUM(campaign_cost)",
        "USD",
        "warehouse.fact_campaign",
        "0 3 * * 1",
        "Marketing",
    ),
]

# 45 features from customer_features (03_DATABASE.md §6.1)
FEATURES: list[tuple[str, str, str, str, str, str, str]] = [
    # (feature_name, feature_table, description, formula, data_source, data_type, version)
    (
        "tenure_days",
        "customer_features",
        "Days since join_date",
        "CURRENT_DATE - join_date",
        "warehouse.dim_customer",
        "INTEGER",
        "v1.0.0",
    ),
    (
        "customer_age",
        "customer_features",
        "Customer age at generation",
        "age",
        "warehouse.dim_customer",
        "INTEGER",
        "v1.0.0",
    ),
    (
        "contract_duration_months",
        "customer_features",
        "Months since contract start",
        "DATEDIFF(month, join_date, now)",
        "warehouse.dim_customer",
        "INTEGER",
        "v1.0.0",
    ),
    (
        "is_postpaid",
        "customer_features",
        "Contract is postpaid",
        "contract_type = 'postpaid'",
        "warehouse.dim_customer",
        "BOOLEAN",
        "v1.0.0",
    ),
    (
        "is_prepaid",
        "customer_features",
        "Contract is prepaid",
        "contract_type = 'prepaid'",
        "warehouse.dim_customer",
        "BOOLEAN",
        "v1.0.0",
    ),
    (
        "avg_daily_data_mb",
        "customer_features",
        "Mean daily data last 90 days",
        "AVG(data_usage_mb) OVER 90d",
        "warehouse.fact_usage_daily",
        "DECIMAL",
        "v1.0.0",
    ),
    (
        "avg_daily_voice_min",
        "customer_features",
        "Mean daily voice last 90 days",
        "AVG(voice_minutes) OVER 90d",
        "warehouse.fact_usage_daily",
        "DECIMAL",
        "v1.0.0",
    ),
    (
        "data_usage_trend",
        "customer_features",
        "Slope of data usage over 90d",
        "REGR_SLOPE(data, date) OVER 90d",
        "warehouse.fact_usage_daily",
        "DECIMAL",
        "v1.0.0",
    ),
    (
        "voice_usage_trend",
        "customer_features",
        "Slope of voice usage over 90d",
        "REGR_SLOPE(voice, date) OVER 90d",
        "warehouse.fact_usage_daily",
        "DECIMAL",
        "v1.0.0",
    ),
    (
        "weekend_usage_ratio",
        "customer_features",
        "Weekend data / total data 90d",
        "SUM(weekend_data) / SUM(data)",
        "warehouse.fact_usage_daily",
        "DECIMAL",
        "v1.0.0",
    ),
    (
        "night_usage_ratio",
        "customer_features",
        "Night data / total data 90d",
        "SUM(night_data) / SUM(data)",
        "warehouse.fact_usage_daily",
        "DECIMAL",
        "v1.0.0",
    ),
    (
        "peak_usage_ratio",
        "customer_features",
        "Peak data / total data 90d",
        "SUM(peak_usage_mb) / SUM(data_usage_mb)",
        "warehouse.fact_usage_daily",
        "DECIMAL",
        "v1.0.0",
    ),
    (
        "roaming_ratio",
        "customer_features",
        "Roaming data / total data 90d",
        "SUM(roaming_usage_mb) / SUM(data_usage_mb)",
        "warehouse.fact_usage_daily",
        "DECIMAL",
        "v1.0.0",
    ),
    (
        "international_ratio",
        "customer_features",
        "Intl minutes / total minutes 90d",
        "SUM(international_minutes) / SUM(voice_minutes)",
        "warehouse.fact_usage_daily",
        "DECIMAL",
        "v1.0.0",
    ),
    (
        "arpu",
        "customer_features",
        "Average monthly revenue 6 months",
        "AVG(net_revenue) OVER 6m",
        "warehouse.fact_billing",
        "DECIMAL",
        "v1.0.0",
    ),
    (
        "revenue_trend",
        "customer_features",
        "Slope of net_revenue 6 months",
        "REGR_SLOPE(net_revenue, month) OVER 6m",
        "warehouse.fact_billing",
        "DECIMAL",
        "v1.0.0",
    ),
    (
        "discount_ratio",
        "customer_features",
        "Avg discount / package price",
        "AVG(discount_amount / package_price)",
        "warehouse.fact_billing",
        "DECIMAL",
        "v1.0.0",
    ),
    (
        "payment_delay_avg",
        "customer_features",
        "Mean overdue days 6 months",
        "AVG(overdue_days) OVER 6m",
        "warehouse.fact_billing",
        "DECIMAL",
        "v1.0.0",
    ),
    (
        "overdue_count",
        "customer_features",
        "Months with overdue payment 6m",
        "COUNT WHERE payment_status='overdue'",
        "warehouse.fact_billing",
        "INTEGER",
        "v1.0.0",
    ),
    (
        "drop_rate_avg",
        "customer_features",
        "Mean drop_rate 90 days",
        "AVG(drop_rate) OVER 90d",
        "warehouse.fact_network",
        "DECIMAL",
        "v1.0.0",
    ),
    (
        "drop_rate_trend",
        "customer_features",
        "Slope of drop_rate 90 days",
        "REGR_SLOPE(drop_rate, date) OVER 90d",
        "warehouse.fact_network",
        "DECIMAL",
        "v1.0.0",
    ),
    (
        "latency_avg_ms",
        "customer_features",
        "Mean latency 90 days",
        "AVG(latency_ms) OVER 90d",
        "warehouse.fact_network",
        "DECIMAL",
        "v1.0.0",
    ),
    (
        "latency_trend",
        "customer_features",
        "Slope of latency 90 days",
        "REGR_SLOPE(latency_ms, date) OVER 90d",
        "warehouse.fact_network",
        "DECIMAL",
        "v1.0.0",
    ),
    (
        "coverage_score_avg",
        "customer_features",
        "Mean coverage score 90 days",
        "AVG(coverage_score) OVER 90d",
        "warehouse.fact_network",
        "DECIMAL",
        "v1.0.0",
    ),
    (
        "signal_stability",
        "customer_features",
        "1 - std(signal)/mean 90d",
        "1 - STDDEV(signal_strength)/AVG(signal_strength)",
        "warehouse.fact_network",
        "DECIMAL",
        "v1.0.0",
    ),
    (
        "network_quality_index",
        "customer_features",
        "Composite: coverage - drop - latency penalty",
        "coverage - drop*100 - latency/50",
        "warehouse.fact_network",
        "DECIMAL",
        "v1.0.0",
    ),
    (
        "complaint_frequency",
        "customer_features",
        "Tickets per day 90 days",
        "SUM(ticket_count) / 90",
        "warehouse.fact_service",
        "DECIMAL",
        "v1.0.0",
    ),
    (
        "complaint_trend",
        "customer_features",
        "Slope of ticket_count 90 days",
        "REGR_SLOPE(ticket_count, date) OVER 90d",
        "warehouse.fact_service",
        "DECIMAL",
        "v1.0.0",
    ),
    (
        "network_complaint_ratio",
        "customer_features",
        "Network complaints / total",
        "network_complaints / total_complaints",
        "warehouse.fact_service",
        "DECIMAL",
        "v1.0.0",
    ),
    (
        "billing_complaint_ratio",
        "customer_features",
        "Billing complaints / total",
        "billing_complaints / total_complaints",
        "warehouse.fact_service",
        "DECIMAL",
        "v1.0.0",
    ),
    (
        "avg_resolution_time_min",
        "customer_features",
        "Mean resolution time 90 days",
        "AVG(resolution_time_min) OVER 90d",
        "warehouse.fact_service",
        "DECIMAL",
        "v1.0.0",
    ),
    (
        "avg_waiting_time_min",
        "customer_features",
        "Mean waiting time 90 days",
        "AVG(waiting_time_min) OVER 90d",
        "warehouse.fact_service",
        "DECIMAL",
        "v1.0.0",
    ),
    (
        "csat_avg",
        "customer_features",
        "Mean CSAT 90 days",
        "AVG(csat_score) WHERE csat IS NOT NULL",
        "warehouse.fact_service",
        "DECIMAL",
        "v1.0.0",
    ),
    (
        "csat_trend",
        "customer_features",
        "Slope of CSAT 90 days",
        "REGR_SLOPE(csat, date) OVER 90d",
        "warehouse.fact_service",
        "DECIMAL",
        "v1.0.0",
    ),
    (
        "escalation_frequency",
        "customer_features",
        "Escalations per day 90 days",
        "SUM(escalation_count) / 90",
        "warehouse.fact_service",
        "DECIMAL",
        "v1.0.0",
    ),
    (
        "package_upgrade_count",
        "customer_features",
        "Package upgrades lifetime",
        "COUNT(package changes upward)",
        "warehouse.fact_billing",
        "INTEGER",
        "v1.0.0",
    ),
    (
        "package_downgrade_count",
        "customer_features",
        "Package downgrades lifetime",
        "COUNT(package changes downward)",
        "warehouse.fact_billing",
        "INTEGER",
        "v1.0.0",
    ),
    (
        "promotion_response_rate",
        "customer_features",
        "Converted / total campaign touches",
        "SUM(converted) / COUNT(*)",
        "warehouse.fact_campaign",
        "DECIMAL",
        "v1.0.0",
    ),
    (
        "recharge_frequency",
        "customer_features",
        "Days between recharges (prepaid)",
        "AVG(days between billing events)",
        "warehouse.fact_billing",
        "DECIMAL",
        "v1.0.0",
    ),
    (
        "data_quota_utilization",
        "customer_features",
        "avg_daily_data*30 / data_quota",
        "avg_daily_data_mb * 30 / (data_quota_gb * 1024)",
        "warehouse.fact_usage_daily",
        "DECIMAL",
        "v1.0.0",
    ),
    (
        "days_since_last_complaint",
        "customer_features",
        "Days since most recent ticket",
        "CURRENT_DATE - MAX(ticket_date)",
        "warehouse.fact_service",
        "INTEGER",
        "v1.0.0",
    ),
    (
        "days_since_last_campaign",
        "customer_features",
        "Days since most recent campaign touch",
        "CURRENT_DATE - MAX(campaign_date)",
        "warehouse.fact_campaign",
        "INTEGER",
        "v1.0.0",
    ),
    (
        "is_heavy_user",
        "customer_features",
        "Top 20% by data usage",
        "avg_daily_data_mb > PERCENTILE(80)",
        "warehouse.fact_usage_daily",
        "BOOLEAN",
        "v1.0.0",
    ),
    (
        "is_premium",
        "customer_features",
        "Premium package or arpu > P80",
        "package_type='premium' OR arpu > PERCENTILE(80)",
        "warehouse.dim_package",
        "BOOLEAN",
        "v1.0.0",
    ),
]


async def seed_dim_time() -> None:
    """Populate dim_time with all dates from 2020 to 2030."""
    async with engine.begin() as conn:
        rows = []
        current = TIME_START
        while current <= TIME_END:
            dow = current.isoweekday()  # 1=Mon ... 7=Sun
            iso_year, iso_week, _ = current.isocalendar()
            rows.append(
                (
                    int(current.strftime("%Y%m%d")),
                    current,
                    current.year,
                    (current.month - 1) // 3 + 1,
                    current.month,
                    iso_week,
                    current.day,
                    dow,
                    ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"][
                        dow - 1
                    ],
                    dow >= 6,
                    current.year,
                    (current.month - 1) // 3 + 1,
                )
            )
            current += timedelta(days=1)

        for row in rows:
            await conn.execute(
                text(
                    "INSERT INTO warehouse.dim_time "
                    "(date_id, full_date, year, quarter, month, week, day, day_of_week, day_name, is_weekend, fiscal_year, fiscal_quarter) "
                    "VALUES (:date_id, :full_date, :year, :quarter, :month, :week, :day, :day_of_week, :day_name, :is_weekend, :fiscal_year, :fiscal_quarter) "
                    "ON CONFLICT (date_id) DO NOTHING"
                ),
                {
                    "date_id": row[0],
                    "full_date": row[1],
                    "year": row[2],
                    "quarter": row[3],
                    "month": row[4],
                    "week": row[5],
                    "day": row[6],
                    "day_of_week": row[7],
                    "day_name": row[8],
                    "is_weekend": row[9],
                    "fiscal_year": row[10],
                    "fiscal_quarter": row[11],
                },
            )
        print(f"dim_time seeded: {len(rows)} rows ({TIME_START} → {TIME_END})")


async def seed_metric_registry() -> None:
    """Populate metric_registry with 50 standardized KPI definitions."""
    async with engine.begin() as conn:
        for metric in METRICS:
            name, category, definition, formula, unit, source, cron, owner = metric
            await conn.execute(
                text(
                    "INSERT INTO semantic.metric_registry "
                    "(metric_name, category, business_definition, formula, unit, data_source, refresh_cron, owner, version) "
                    "VALUES (:name, :category, :definition, :formula, :unit, :source, :cron, :owner, 'v1.0.0') "
                    "ON CONFLICT (metric_name) DO NOTHING"
                ),
                {
                    "name": name,
                    "category": category,
                    "definition": definition,
                    "formula": formula,
                    "unit": unit,
                    "source": source,
                    "cron": cron,
                    "owner": owner,
                },
            )
        print(f"metric_registry seeded: {len(METRICS)} KPIs")


async def seed_feature_registry() -> None:
    """Populate feature_registry with 44 customer features."""
    async with engine.begin() as conn:
        for feature in FEATURES:
            name, table, description, formula, source, dtype, version = feature
            await conn.execute(
                text(
                    "INSERT INTO feature_store.feature_registry "
                    "(feature_name, feature_table, description, formula, data_source, data_type, version, owner) "
                    "VALUES (:name, :table, :description, :formula, :source, :dtype, :version, 'ML Team') "
                    "ON CONFLICT (feature_name) DO NOTHING"
                ),
                {
                    "name": name,
                    "table": table,
                    "description": description,
                    "formula": formula,
                    "source": source,
                    "dtype": dtype,
                    "version": version,
                },
            )
        print(f"feature_registry seeded: {len(FEATURES)} features")


async def main() -> None:
    await seed_dim_time()
    await seed_metric_registry()
    await seed_feature_registry()
    await engine.dispose()


if __name__ == "__main__":
    asyncio.run(main())
