"""make dimension surrogate keys auto-generating identity

Revision ID: e5f6a7b8c9d0
Revises: d4e5f6a7b8c9
Create Date: 2026-08-12
"""

from collections.abc import Sequence

from alembic import op

revision: str = "e5f6a7b8c9d0"
down_revision: str | None = "d4e5f6a7b8c9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Convert surrogate integer PKs to auto-generating identity columns."""
    op.execute(
        "ALTER TABLE warehouse.dim_package "
        "ALTER COLUMN package_id ADD GENERATED BY DEFAULT AS IDENTITY"
    )
    op.execute(
        "ALTER TABLE warehouse.dim_customer "
        "ALTER COLUMN customer_id ADD GENERATED BY DEFAULT AS IDENTITY"
    )
    op.execute(
        "ALTER TABLE warehouse.dim_region "
        "ALTER COLUMN region_id ADD GENERATED BY DEFAULT AS IDENTITY"
    )


def downgrade() -> None:
    """Drop identity generation (destructive — reverts the migration)."""
    op.execute("ALTER TABLE warehouse.dim_package ALTER COLUMN package_id DROP IDENTITY")
    op.execute("ALTER TABLE warehouse.dim_customer ALTER COLUMN customer_id DROP IDENTITY")
    op.execute("ALTER TABLE warehouse.dim_region ALTER COLUMN region_id DROP IDENTITY")
